-- Migration: Seed initial hack data
-- This migration populates the hacks table with 15 sample hacks across different categories

INSERT INTO hacks (
  title,
  description,
  category,
  difficulty,
  why_it_works,
  content_type,
  content_url,
  content_thumbnail,
  source_attribution,
  source_platform,
  worked_votes,
  failed_votes,
  unique_users_who_validated,
  status,
  created_by
) VALUES
-- COOKING HACKS
(
  'Remove Burnt Rice in 30 Seconds',
  'Add water and heat. The burnt layer comes right off.',
  'Cooking',
  'easy',
  'Water creates steam that separates the burnt layer from the pot. Works on any burnt grain.',
  'video',
  'https://www.youtube.com/watch?v=example1',
  'https://img.youtube.com/vi/example1/default.jpg',
  'CookingWithSarah',
  'YouTube',
  87,
  12,
  5,
  'approved',
  'admin'
),
(
  'Perfect Scrambled Eggs Every Time',
  'Low heat, constant stirring, remove at 80% cooked.',
  'Cooking',
  'easy',
  'Eggs continue cooking from residual heat. Low heat prevents overcooking and rubber texture.',
  'video',
  'https://www.tiktok.com/@chefmike/example2',
  'https://p16-sign.tiktokcdn.com/example2.jpg',
  'chefmike',
  'TikTok',
  65,
  8,
  3,
  'approved',
  'admin'
),
(
  'Defrost Chicken in 30 Minutes',
  'Use cold water in a ziplock bag, change water every 5 minutes.',
  'Cooking',
  'medium',
  'Cold water conducts heat through the bag better than air. Prevents bacterial growth.',
  'link',
  'https://www.reddit.com/r/Cooking/example3',
  NULL,
  'r/Cooking',
  'Reddit',
  42,
  5,
  2,
  'approved',
  'admin'
),
-- CLEANING HACKS
(
  'Clean Windows with Vinegar and Newspaper',
  'Spray vinegar solution, wipe with crumpled newspaper for streak-free shine.',
  'Cleaning',
  'easy',
  'Vinegar cuts through grease and film. Newspaper doesn''t leave lint like paper towels.',
  'video',
  'https://www.youtube.com/watch?v=example4',
  'https://img.youtube.com/vi/example4/default.jpg',
  'CleanMySpace',
  'YouTube',
  134,
  18,
  8,
  'approved',
  'admin'
),
(
  'Remove Carpet Stains with Ice',
  'Place ice cubes on stain, let melt, then vacuum and blot.',
  'Cleaning',
  'easy',
  'Ice liquefies the stain without saturating carpet fibers. Cold prevents setting.',
  'video',
  'https://www.instagram.com/p/example5',
  'https://instagram.example.com/example5.jpg',
  'CleanHomeDaily',
  'Instagram',
  53,
  7,
  3,
  'approved',
  'admin'
),
(
  'Remove Coffee Smell from Containers',
  'Fill with vinegar and baking soda, let sit overnight, rinse.',
  'Cleaning',
  'medium',
  'Vinegar breaks down odor molecules. Baking soda absorbs remaining scents.',
  'link',
  'https://www.reddit.com/r/HomeImprovement/example6',
  NULL,
  'r/HomeImprovement',
  'Reddit',
  31,
  4,
  1,
  'approved',
  'admin'
),
-- MONEY HACKS
(
  'Negotiate Your Utility Bills',
  'Call provider, say you''re switching, ask for loyalty discount. Usually saves $50-100/year.',
  'Money',
  'medium',
  'Companies value customer retention. They have authority to offer discounts to prevent churn.',
  'link',
  'https://www.reddit.com/r/personalfinance/example7',
  NULL,
  'r/personalfinance',
  'Reddit',
  78,
  11,
  4,
  'approved',
  'admin'
),
(
  'Find Hidden Bank Fees and Remove Them',
  'Review last 3 months of statements. Call and ask for fee reversals.',
  'Money',
  'medium',
  'Banks are willing to reverse fees for good customers. Most people never ask.',
  'link',
  'https://example-finance-blog.com/hidden-fees',
  NULL,
  'PersonalFinanceBlog',
  'Blog',
  29,
  3,
  1,
  'approved',
  'admin'
),
-- TECH HACKS
(
  'Speed Up Your WiFi Router Instantly',
  'Restart router weekly. Position antenna vertically. Keep away from metal/water.',
  'Tech',
  'easy',
  'Restarts clear memory leaks. Vertical antennas transmit better in homes. Metal/water absorb signal.',
  'video',
  'https://www.youtube.com/watch?v=example8',
  'https://img.youtube.com/vi/example8/default.jpg',
  'TechTips101',
  'YouTube',
  119,
  14,
  6,
  'approved',
  'admin'
),
(
  'Free Up Phone Storage Instantly',
  'Delete old photos from Recently Deleted folder. Clear app caches.',
  'Tech',
  'easy',
  'Recently Deleted folder still takes space. App caches accumulate GB of data over time.',
  'video',
  'https://www.tiktok.com/@techsolutions/example9',
  'https://p16-sign.tiktokcdn.com/example9.jpg',
  'techsolutions',
  'TikTok',
  67,
  9,
  3,
  'approved',
  'admin'
),
-- HOME/DIY HACKS
(
  'Fix Squeaky Door Hinges Without Tools',
  'Put a drop of olive oil on the hinge. Rotate door back and forth.',
  'Home',
  'easy',
  'Oil lubricates friction points. Movement distributes oil evenly.',
  'video',
  'https://www.instagram.com/p/example10',
  'https://instagram.example.com/example10.jpg',
  'DIYHomeHacks',
  'Instagram',
  102,
  8,
  5,
  'approved',
  'admin'
),
(
  'Remove Wallpaper with Fabric Softener',
  'Mix fabric softener with hot water, spray, wait 15 min, scrape gently.',
  'Home',
  'medium',
  'Softener breaks adhesive bonds. Heat softens glue. Waiting prevents wall damage.',
  'video',
  'https://www.youtube.com/watch?v=example11',
  'https://img.youtube.com/vi/example11/default.jpg',
  'HomeRenovationPro',
  'YouTube',
  76,
  10,
  3,
  'approved',
  'admin'
),
-- BEAUTY HACKS
(
  'DIY Makeup Setting Spray with 2 Ingredients',
  'Mix coconut water and vitamin spray. Spray lightly after makeup.',
  'Beauty',
  'easy',
  'Coconut water hydrates without messing up makeup. Vitamin E seals everything.',
  'video',
  'https://www.tiktok.com/@beautyhacks/example12',
  'https://p16-sign.tiktokcdn.com/example12.jpg',
  'beautyhacks',
  'TikTok',
  45,
  6,
  2,
  'approved',
  'admin'
),
(
  'Remove Dark Circles Naturally',
  'Brew green tea bags, refrigerate, place on eyes for 10 minutes each morning.',
  'Beauty',
  'medium',
  'Green tea has caffeine and antioxidants. Cold reduces puffiness.',
  'link',
  'https://www.reddit.com/r/SkincareAddiction/example13',
  NULL,
  'r/SkincareAddiction',
  'Reddit',
  38,
  5,
  2,
  'approved',
  'admin'
),
-- TRAVEL HACK
(
  'Pack 50% Less Clothing with Roll Method',
  'Roll clothes tightly instead of folding. Stack vertically in luggage.',
  'Travel',
  'easy',
  'Rolling uses 40% less space. Vertical stacking lets you see everything. Easy to find items.',
  'video',
  'https://www.youtube.com/watch?v=example14',
  'https://img.youtube.com/vi/example14/default.jpg',
  'TravelWithSam',
  'YouTube',
  92,
  7,
  4,
  'approved',
  'admin'
),
-- PRODUCTIVITY HACK
(
  'Boost Focus with 2-Minute Pre-Task Ritual',
  'Drink water, stretch, write one sentence about your goal. Start immediately.',
  'Productivity',
  'easy',
  'Water hydrates brain. Stretching increases blood flow. Writing commits you to goal.',
  'link',
  'https://www.reddit.com/r/productivity/example15',
  NULL,
  'r/productivity',
  'Reddit',
  53,
  8,
  2,
  'approved',
  'admin'
);
